---
title: "Final project"
author: "Hannah Sutoris, Baylie Larsen, Nicole Masuoka"
date: "2023-12-08"
output: html_document
---

## Introduction


## Methods


## Results


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rgbif)
library(tidyverse)
library(MuMIn)
library(rnoaa)
library(data.table)
library(ggmap)
library(usmap)
library(magick)
library(cowplot)
library(lme4)
library(car)
library(sf)
library(knitr)
library(kableExtra)
```

```{r, echo=FALSE, message=FALSE}
whale_data <-read.csv("Whale_data2.csv")

meanC <- mean(whale_data$Cortisol)
print(meanC)

# 
# # ggplot(subset(whale_data, Preg != "Male", Year != "2021"), aes(x=Preg, y=Cortisol, fill=Preg))+
# #      geom_boxplot()+
# #      labs(title="data",x="pregnant", y="cortisol")
# 
# covid_whale_data <- subset(whale_data, Year == 2021)
# after_covid_plot <- ggplot(subset(covid_whale_data, Preg != "Male"), aes(x=Preg, y=Cortisol, fill=Preg))+
#   geom_boxplot()+
#   labs(title="data",x="pregnant", y="cortisol")
# after_covid_plot

library(ggplot2)
library(gridExtra)

y_axis_breaks <- seq(0.1, 1, by = 0.2)
y_axis_labels <- seq(0.1, 1, by = 0.2)

# Create the first box plot
before_covid_plot <- ggplot(subset(whale_data, Preg != "Male" & Year != 2021), aes(x = Preg, y = Cortisol, fill = Preg)) +
  geom_boxplot() +
  labs(title = "Before COVID Data", x = "Pregnant", y = "Cortisol") +
  scale_y_continuous(breaks = y_axis_breaks, labels = y_axis_labels) +
  theme_minimal()

# Create the second box plot
y_axis_breaks_after <- seq(0.1, 1, by = 0.2)
y_axis_labels_after <- seq(0.1, 1, by = 0.2)
covid_whale_data <- subset(whale_data, Year == 2021)
after_covid_plot <- ggplot(subset(covid_whale_data, Preg != "Male"), aes(x = Preg, y = Cortisol, fill = Preg)) +
  geom_boxplot() +
  labs(title = "During COVID Data", x = "Pregnant", y = "Cortisol") +
  scale_y_continuous(breaks = y_axis_breaks_after, labels = y_axis_labels_after) +
  theme_minimal()

# Combine the two plots
grid.arrange(before_covid_plot, after_covid_plot, ncol = 2)

#aic/dredge of 3 variables
library(lme4)
library(MuMIn)
whale_data <-read.csv("whale_data.csv")
whale_models <- dredge(lm(Cortisol ~ Preg + Voyages + Year, data = whale_data, na.action = "na.fail"))

print(whale_models)

#New portion!!

# adding covid years
whale_data$covid <- character(nrow(whale_data)) 
for (i in seq_along(whale_data$Voyages)) {
  if (whale_data$Voyages[i] > 100) {
    whale_data$covid[i] <- "Not Covid"
  } else {
    whale_data$covid[i] <- "Covid"
  }
}


#Anova
library(dplyr)
whale_data$logCort <- log(whale_data$Cortisol)

anova_whales <- aov(lm(logCort~Preg*covid, data=whale_data))

print(anova_whales)

#Tukey
tukey_result <- TukeyHSD(anova_whales)

# Print post-hoc test results
print(tukey_result)



library(ggplot2)
ggplot(whale_data,aes(x=Preg,y=logCort,col=covid))+
  geom_boxplot()+
  xlab("Pregnant")+
  ylab("Log Cortisol")+
  guides(color=guide_legend(title="Covid"))+
  theme_classic()
```

## Discussion



## Author Contributions